# Generated by Django 5.0 on 2026-05-20 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='audio_generations_left',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.CreateModel(
            name='AudiobookProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audiobooks/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks', to='App.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
